on:
  push:
    branches:
      - master
  pull_request:

name: lint

jobs:
  fmt:
    name: rust fmt
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set default toolchain
        run: rustup default nightly

      - name: Set profile
        run: rustup set profile minimal

      - name: Add rustfmt
        run: rustup component add rustfmt

      - name: Add clippy
        run: rustup component add clippy

      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: brew install automake libtool zeromq

      - name: Update toolchain
        run: rustup update

      - name: Check fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
